### ISSUE TITLE
multiple commands

### ISSUE THREAD

**Issue by mbana** [abiosoft/parent#1]
do this allow running multiple commands, if so, how?

thanks,

**Comment by abiosoft** [comment]
Yeah. You can look how it is used here https://github.com/abiosoft/caddy-docker/blob/master/Dockerfile#L45-L46

**Comment by mbana** [comment]
i meant, say, run `ls -lah` before `caddy` is started. can you currently do that when the `Dockerfile` has:

```sh
ENTRYPOINT ["/bin/parent", "caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=$ACME_AGREE"]
```

so, i'd like say `ls -alh /root/.caddy && caddy`.

**Comment by abiosoft** [comment]
In that case, you'd override the entrypoint. e.g.
```
docker run -it --entrypoint sh abiosoft/caddy -c "ls -lah /root/.caddy && caddy"
```

**Comment by mbana** [comment]
that's not ideal, but thanks. i was hoping you might add support for it in the `Dockerfile`.
